"""Core task, connection, evidence, and scenario contracts for lstest."""

from __future__ import annotations

import csv
import hashlib
import json
import sys
import shutil
import threading
import time
from dataclasses import asdict, dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping, Protocol, Sequence

try:
    from .observations import RawTag, ToolJudgement, raw_tags_from_mappings, render_observation
    from .timeline import TimelineLedger, ToolLogValidator, safe_basename
except ImportError:  # direct execution fallback
    from observations import RawTag, ToolJudgement, raw_tags_from_mappings, render_observation
    from timeline import TimelineLedger, ToolLogValidator, safe_basename

BEIJING = timezone(timedelta(hours=8))
STICKY_FATAL_MARKERS = {
    "PANIC", "CRASH", "ASSERT", "WATCHDOG_RESET", "UNEXPECTED_REBOOT",
    "DATA_CORRUPTION", "SERIAL_LOSS", "TOOL_EXCEPTION",
}
NORMAL_CASE_STATUSES = {"PASS", "EXPECTED"}
# ``facts_json`` is an auditable result field generated by this runtime.  The
# stdlib CSV default is only 128 KiB, which is too small for legitimate
# cross-scenario summaries.  Keep a finite per-field ceiling to avoid turning
# a malformed result file into an unbounded memory read at finalization.
RESULT_CSV_FIELD_LIMIT = 16 * 1024 * 1024

# Human-readable tool.log is deliberately rendered by this allow-list.  An
# adapter may emit a new internal event name, but it cannot introduce a new
# line shape or bracket label; unknown events use the fixed SYSTEM shape.
LOG_NODE_LABELS = {"CASE", "ACTION", "DEVICE", "ONLINE", "PLAYER", "RESULT", "COMMAND", "ERROR", "SUMMARY", "SYSTEM"}
LOG_FACT_KEYS = {
    "TASK", "INIT_WAIT", "INIT_READY", "INIT_STABLE", "RESTART", "LOG_LEVEL", "COMMAND",
    "WAKE", "OFFLINE_TONE", "OFFLINE_ASR", "OFFLINE_INTENT", "OFFLINE_TEXT",
    "OFFLINE_NORMALIZED", "ONLINE_ASR", "REQUEST_ID", "RESPONSE_ID",
    "ASR_LATENCY_MS", "PLAY_URL", "AUDIO_FILE", "BROADCAST_ID", "PLAYER",
}


def now_dt() -> datetime:
    return datetime.now(BEIJING)


def now_iso() -> str:
    return now_dt().isoformat(timespec="milliseconds")


def now_human() -> str:
    return now_dt().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


@dataclass(frozen=True)
class PortSpec:
    port: str
    baudrate: int
    role: str | None = None
    capabilities: tuple[str, ...] = ()
    required_for: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        result = asdict(self)
        result["capabilities"] = list(self.capabilities)
        result["required_for"] = list(self.required_for)
        return result


@dataclass(frozen=True)
class ConnectionSpec:
    ports: tuple[PortSpec, ...] = ()
    playback_device_key: str | None = None
    capture_device_key: str | None = None
    profile_id: str | None = None
    result_root: Path = Path("result")

    def to_dict(self) -> dict[str, Any]:
        return {
            "ports": [item.to_dict() for item in self.ports],
            "playback_device_key": self.playback_device_key,
            "playback_target_mode": "specified_device_key" if self.playback_device_key else "system_default_render",
            "capture_device_key": self.capture_device_key,
            "profile_id": self.profile_id,
            "result_root": str(self.result_root),
        }

    @classmethod
    def from_mapping(cls, payload: Mapping[str, Any]) -> "ConnectionSpec":
        raw_ports = payload.get("ports") or []
        ports: list[PortSpec] = []
        for raw in raw_ports:
            if isinstance(raw, str):
                parts = raw.split(":")
                raw = {"port": parts[0], "role": parts[1] if len(parts) > 1 else None}
            if not isinstance(raw, Mapping):
                raise ValueError("each port must be a string or object")
            port = str(raw.get("port", "")).strip()
            if not port:
                raise ValueError("port cannot be empty")
            baudrate = int(raw.get("baudrate", payload.get("baudrate", 0)))
            if baudrate <= 0:
                raise ValueError(f"invalid baudrate for {port}")
            ports.append(PortSpec(
                port=port,
                baudrate=baudrate,
                role=str(raw["role"]).strip() if raw.get("role") else None,
                capabilities=tuple(str(value) for value in raw.get("capabilities", ())),
                required_for=tuple(str(value) for value in raw.get("required_for", ())),
            ))
        return cls(
            ports=tuple(ports),
            playback_device_key=payload.get("playback_device_key"),
            capture_device_key=payload.get("capture_device_key"),
            profile_id=payload.get("profile_id"),
            result_root=Path(payload.get("result_root", "result")),
        )


@dataclass
class CaseResult:
    case_id: str
    raw_status: str
    reviewed_status: str | None = None
    reason: str = ""
    evidence: list[str] = field(default_factory=list)
    facts: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class CaseSpec:
    case_id: str
    text: str = ""
    audio_path: str | None = None
    domain: str | None = None
    intent: str | None = None
    action: str | None = None
    destructive: bool = False
    metadata: Mapping[str, Any] = field(default_factory=dict)


@dataclass
class ObservedFacts:
    case_id: str
    markers: list[dict[str, Any]] = field(default_factory=list)
    wake: dict[str, Any] = field(default_factory=dict)
    asr: dict[str, Any] = field(default_factory=dict)
    business: dict[str, Any] = field(default_factory=dict)
    player: dict[str, Any] = field(default_factory=dict)
    correlation: dict[str, Any] = field(default_factory=dict)
    timing: dict[str, Any] = field(default_factory=dict)
    evidence: list[str] = field(default_factory=list)


class Scenario(Protocol):
    """Scenario contract implemented by project adapters."""

    def preflight(self, runtime: "DeviceRuntime") -> None: ...
    def next_case(self, state: Any) -> CaseSpec | None: ...
    def run_case(self, case: CaseSpec, runtime: "DeviceRuntime") -> ObservedFacts: ...
    def judge(self, observed: ObservedFacts) -> CaseResult: ...
    def cleanup(self, runtime: "DeviceRuntime") -> None: ...


class StopSupervisor:
    def __init__(self, stop_file: Path, *, disk_limit_bytes: int = 1024**3):
        self.stop_file = stop_file
        self.disk_limit_bytes = disk_limit_bytes
        self._event = threading.Event()
        self.reason = ""

    def request(self, reason: str = "requested") -> None:
        self.reason = reason
        self._event.set()

    @property
    def requested(self) -> bool:
        return self._event.is_set() or self.stop_file.is_file()

    def disk_ok(self, path: Path) -> bool:
        try:
            return path.stat().st_size >= 0 and shutil.disk_usage(path).free > self.disk_limit_bytes
        except OSError:
            return False

    def check(self, path: Path | None = None) -> str | None:
        """返回停止原因；磁盘低于停止线时阻止新的用例。"""
        if self.stop_file.is_file():
            return self.reason or "STOP_FILE"
        if path is not None and not self.disk_ok(path):
            self.request("DISK_STOP_LINE")
            return self.reason
        return self.reason if self.requested else None

    def wait(self, seconds: float, *, tick: float = 0.1, path: Path | None = None) -> str | None:
        """可中断、有上限的等待；永不向 time.sleep 传递负数。"""
        duration = max(0.0, float(seconds))
        deadline = time.monotonic() + duration
        while True:
            reason = self.check(path)
            if reason:
                return reason
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                return None
            self._event.wait(min(max(0.01, tick), remaining))

    def raise_if_requested(self, path: Path | None = None) -> None:
        reason = self.check(path)
        if reason:
            raise RuntimeError(reason)


class StopPolicy:
    """The only task-level stop gate.

    A case failure, parser failure, device error, recovery exhaustion, or a
    callback exception is deliberately *not* a task stop.  These conditions
    stay visible in the current case and the supervisor continues with the
    next runnable case.  The small whitelist below reflects conditions where
    continuing would make the evidence untrustworthy or unsafe.
    """

    ALLOWED = frozenset({
        "USER_STOP",
        "EVIDENCE_WRITE_FAILURE",
        "BLOCKED_PROFILE_CONTRACT",
        "INFRASTRUCTURE_UNAVAILABLE",
        "PROFILE_SAFETY_STOP",
        "DISK_STOP_LINE",
    })

    def __init__(self, stop: StopSupervisor) -> None:
        self.stop = stop
        self.records: list[dict[str, Any]] = []

    def request(self, code: str, *, reason: str = "", **details: Any) -> bool:
        normalized = str(code or "").strip().upper()
        if normalized not in self.ALLOWED:
            return False
        self.records.append({"code": normalized, "reason": reason, "details": dict(details), "at": now_iso()})
        self.stop.request(normalized)
        return True

    def check(self, path: Path) -> str | None:
        raw = self.stop.check(path)
        if not raw:
            return None
        if raw in {"STOP_FILE", "requested"}:
            self.request("USER_STOP", reason="用户请求停止")
            return "USER_STOP"
        if raw == "DISK_STOP_LINE":
            self.request("DISK_STOP_LINE", reason="标准证据存储空间不足")
            return "DISK_STOP_LINE"
        return raw if raw in self.ALLOWED else None


class TaskSupervisor:
    """Contain ordinary action/case exceptions so a stress task can continue."""

    def __init__(self, artifacts: "TaskArtifacts") -> None:
        self.artifacts = artifacts

    def run(self, case_id: str, phase: str, action: Any, fallback: Any = None) -> Any:
        try:
            return action()
        except Exception as error:
            self.artifacts.record_anomaly(
                "TOOL_ACTION_EXCEPTION",
                "工具动作异常，当前轮将继续收尾。",
                case_id=case_id,
                phase=phase,
                error=f"{type(error).__name__}: {error}",
                handling="记录异常并继续当前轮",
            )
            return fallback


class TaskArtifacts:
    """The four-artifact result ledger used by every new lstest task.

    ``serial_logs/`` is the continuous device-side fact source.  ``tool.log``
    is the single human-readable execution ledger.  ``results.csv`` contains
    one final row per logical case, and ``cases.csv`` freezes the input order
    before any device action.  No derived JSON, per-tool log, or summary file
    is created for new tasks.
    """

    TOOL_FIELDS = (
        "time", "level", "event", "task_id", "epoch", "round", "case_id",
        "phase", "source", "device", "port_role", "action_id", "broadcast_id",
        "correlation_id", "status", "reason", "attempt", "max_attempts",
        "elapsed_ms", "rule_id", "expected", "actual", "raw", "normalized",
        "handling", "evidence", "message", "details",
    )
    RESULT_FIELDS = (
        "round", "case_id", "started_at", "ended_at", "epoch", "scenario",
        "input_text", "audio_file", "audio_sha256", "profile_version", "profile_sha256",
        "raw_fact_counts", "logical_fact_counts", "association", "anomaly_codes",
        "primary_reason", "raw_status", "reviewed_status", "final_status", "reason",
        "evidence", "facts_json",
    )
    CASE_FIELDS = (
        "case_order", "case_id", "scenario", "input_text", "audio_file", "audio_sha256",
        "case_contract", "source_file", "source_sha256", "random_seed",
        "profile_version", "profile_sha256",
    )

    def __init__(
        self,
        result_root: Path,
        task_slug: str,
        detail_fields: Sequence[str] = (),
        *,
        terminal_stream: Any | None = None,
    ):
        stamp = now_dt().strftime("%Y%m%d_%H%M%S")
        base = Path(result_root) / f"{stamp}_{task_slug}"
        candidate = base
        suffix = 1
        while candidate.exists():
            candidate = Path(f"{base}_{suffix:02d}")
            suffix += 1
        self.run_dir = candidate
        (self.run_dir / "serial_logs").mkdir(parents=True, exist_ok=False)
        self.task_id = self.run_dir.name
        self.tool_log_path = self.run_dir / "tool.log"
        self.results_path = self.run_dir / "results.csv"
        self.cases_path = self.run_dir / "cases.csv"
        self.stop = StopSupervisor(self.run_dir / "STOP")
        self.stop_policy = StopPolicy(self.stop)
        self._lock = threading.RLock()
        self._tool = self.tool_log_path.open("a", encoding="utf-8")
        self._terminal_stream: Any | None = terminal_stream
        self._terminal_mirror_failure_recorded = False
        self._legacy_stdout_disabled = False
        self.timeline = TimelineLedger(self._append_timeline_line, now_human)
        result_fields = list(dict.fromkeys([*self.RESULT_FIELDS, *detail_fields]))
        self._csv = self.results_path.open("w", encoding="utf-8-sig", newline="")
        self._writer = csv.DictWriter(self._csv, fieldnames=result_fields, extrasaction="ignore")
        self._writer.writeheader()
        self._csv.flush()
        self._cases = self.cases_path.open("w", encoding="utf-8-sig", newline="")
        self._cases_writer = csv.DictWriter(self._cases, fieldnames=self.CASE_FIELDS, extrasaction="ignore")
        self._cases_writer.writeheader()
        self._cases.flush()
        self._cases_frozen = False
        self._frozen_case_count = 0
        self._planned_case_count = 0
        self._lazy_case_mode = False
        self._lazy_case_identity: dict[str, Any] = {}
        self._declared_case_count = 0
        self._case_positions: dict[str, int] = {}
        self._case_metadata: dict[str, dict[str, Any]] = {}
        self.counts: dict[str, int] = {}
        self.exception_counts: dict[str, int] = {}
        self.anomaly_counts: dict[str, int] = {}
        self.completed_cases = 0
        self.sticky: list[dict[str, Any]] = []
        self.capabilities: dict[str, dict[str, Any]] = {}
        self.checks: dict[str, list[dict[str, Any]]] = {}
        self.current_epoch = 0
        self._epoch_listeners: list[Any] = []
        self.health_policy: dict[str, Any] = {}
        self.health_streaks: dict[str, int] = {}
        self._closers: list[tuple[str, Any]] = []
        self._final_summary: dict[str, Any] | None = None
        self.closed = False
        self.timeline.system(
            f"任务开始: task={task_slug}，结果=serial_logs/、tool.log、results.csv、cases.csv",
            epoch=self.current_epoch,
        )

    def _append_timeline_line(self, line: str) -> None:
        """Write renderer-owned lines atomically and flush them for live review."""
        with self._lock:
            try:
                self._tool.write(line)
                self._tool.flush()
            except OSError as error:
                # The result log is the auditable evidence source.  A failure
                # here means the task cannot safely continue.
                self.stop_policy.request(
                    "EVIDENCE_WRITE_FAILURE",
                    reason="tool.log 无法可靠写入",
                    error=f"{type(error).__name__}: {error}",
                )
                raise
            if self._terminal_stream is not None:
                try:
                    self._terminal_stream.write(line)
                    self._terminal_stream.flush()
                except (OSError, ValueError):
                    # A caller can close or lose its terminal pipe while the
                    # task is still collecting device evidence.  The durable
                    # tool.log remains healthy, so keep the case runnable and
                    # record this once without recursively using Timeline.
                    self._terminal_stream = None
                    if not self._terminal_mirror_failure_recorded:
                        self._terminal_mirror_failure_recorded = True
                        self._tool.write(
                            f"{now_human()} [SYSTEM] 终端镜像不可用，后续过程仅写入 tool.log。\n"
                        )
                        self._tool.flush()

    def enable_terminal_mirror(self, stream: Any | None = None) -> None:
        """Mirror exact human-timeline bytes to one terminal stream.

        Only the timeline writer invokes this mirror, so project adapters cannot
        create terminal-only human entries that differ from the tool log.
        """
        self._terminal_stream = stream or sys.stdout

    def _timeline_contract(self, case_id: str) -> dict[str, Any]:
        metadata = self._case_metadata.get(str(case_id), {})
        configured = metadata.get("timeline", {})
        timeline = dict(configured) if isinstance(configured, Mapping) else {}
        expected: set[str] = {str(item).upper() for item in timeline.get("required_facts", ())}
        return {
            "expected_keys": expected,
            "mirror_policy": dict(timeline.get("mirror_policy", {})) if isinstance(timeline.get("mirror_policy", {}), Mapping) else {},
            "mirror_window_ms": int(timeline.get("mirror_window_ms", 120) or 120),
            "reason_labels": dict(timeline.get("reason_labels", {})) if isinstance(timeline.get("reason_labels", {}), Mapping) else {},
            "duplicate_policy": dict(timeline.get("duplicate_policy", {})) if isinstance(timeline.get("duplicate_policy", {}), Mapping) else {},
        }

    def timeline_case_start(self, case_id: str, *, epoch: int | None = None) -> None:
        metadata = self.case_metadata(case_id)
        contract = self._timeline_contract(case_id)
        self.timeline.start_case(
            case_id,
            epoch=self.current_epoch if epoch is None else int(epoch),
            position=self._case_positions.get(case_id, self.completed_cases + 1),
            total=self._planned_case_count or self._frozen_case_count,
            scenario=str(metadata.get("scenario", "")),
            text=str(metadata.get("input_text", "")),
            **contract,
        )

    def timeline_action(self, case_id: str, *, text: str, audio_file: Any, phase: str = "command") -> None:
        self.timeline.action(case_id, text, audio_file, phase=phase)

    def timeline_action_end(
        self,
        case_id: str,
        *,
        text: str,
        audio_file: Any,
        status: str,
        duration_ms: int | None = None,
    ) -> None:
        self.timeline.action_end(
            case_id,
            text,
            audio_file,
            status=status,
            duration_ms=duration_ms,
        )

    def timeline_wait(self, case_id: str, *, action: str, planned_ms: int) -> None:
        self.timeline.wait(case_id, action, planned_ms=planned_ms)

    def timeline_fact(self, case_id: str, key: str, value: Any, **fields: Any) -> Any:
        return self.timeline.fact(case_id, key, value, epoch=int(fields.pop("epoch", self.current_epoch)), **fields)

    def timeline_player(self, case_id: str, state: Any, **fields: Any) -> None:
        self.timeline.player(case_id, state, epoch=int(fields.pop("epoch", self.current_epoch)), **fields)

    @staticmethod
    def _text(value: Any) -> str:
        if value is None or value == "":
            return "-"
        if isinstance(value, str):
            return value.replace("\r\n", "\\n").replace("\n", "\\n")
        if isinstance(value, (Mapping, list, tuple, set)):
            return json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)
        return str(value)

    def _tool_block(self, event: str, level: str, message: str, fields: Mapping[str, Any]) -> str:
        values = dict(fields)
        port = values.pop("port", "")
        role = values.pop("role", "")
        port_role = values.pop("port_role", "") or "/".join(item for item in (str(port), str(role)) if item)
        evidence = values.pop("evidence", values.pop("evidence_refs", ""))
        raw = values.pop("raw", values.pop("raw_tags", values.pop("raw_line", "")))
        normalized = values.pop("normalized", "")
        expected = values.pop("expected", "")
        actual = values.pop("actual", "")
        known = {
            "time": now_human(),
            "level": level.upper(),
            "event": event,
            "task_id": self.task_id,
            "epoch": values.pop("epoch", self.current_epoch),
            "round": values.pop("round", values.pop("completed_cases", "")),
            "case_id": values.pop("case_id", ""),
            "phase": values.pop("phase", ""),
            "source": values.pop("source", ""),
            "device": values.pop("device", ""),
            "port_role": port_role,
            "action_id": values.pop("action_id", ""),
            "broadcast_id": values.pop("broadcast_id", ""),
            "correlation_id": values.pop("correlation_id", values.pop("query_id", values.pop("request_id", ""))),
            "status": values.pop("status", values.pop("tool_status", "")),
            "reason": values.pop("reason", values.pop("tool_reason", "")),
            "attempt": values.pop("attempt", ""),
            "max_attempts": values.pop("max_attempts", ""),
            "elapsed_ms": values.pop("elapsed_ms", values.pop("duration_ms", "")),
            "rule_id": values.pop("rule_id", ""),
            "expected": expected,
            "actual": actual,
            "raw": raw,
            "normalized": normalized,
            "handling": values.pop("handling", ""),
            "evidence": evidence,
            "message": message,
            "details": values,
        }
        return self._render_tool_line(event, level, message, known)

    def _render_tool_line(self, event: str, level: str, message: str, known: Mapping[str, Any]) -> str:
        """Render the compact, two-layer human ledger.

        Device/profile regexes are intentionally hidden here.  They are kept
        in the profile and the continuous serial log is the raw evidence.  The
        main ledger shows only the extracted ``KEY: VALUE`` fact; a judgement
        is rendered on the following line so device facts cannot be confused
        with a tool-derived PASS/FAIL decision.
        """
        event_name = str(event or "EVENT").upper()
        case_id = str(known.get("case_id") or "")
        position = self._case_positions.get(case_id)
        case_prefix = f"{position}/{self._planned_case_count or self._frozen_case_count}" if position else "-/-"
        metadata = self._case_metadata.get(case_id, {})
        raw = known.get("raw")
        raw_text = ""
        raw_items = raw if isinstance(raw, list) else []
        if isinstance(raw, str):
            raw_text = raw
            try:
                raw = json.loads(raw)
            except (TypeError, ValueError):
                pass
        if not isinstance(raw, Mapping):
            if raw_items and all(isinstance(item, Mapping) for item in raw_items):
                raw = {
                    str(item.get("tag_name")): item.get("raw_value")
                    for item in raw_items
                    if str(item.get("tag_name") or "").strip()
                }
            else:
                raw = {}
        normalized = known.get("normalized")
        if not isinstance(normalized, Mapping):
            normalized = {}
        details = known.get("details")
        if not isinstance(details, Mapping):
            details = {}

        def value(*names: str, default: Any = "") -> Any:
            for name in names:
                candidate = known.get(name)
                if candidate not in (None, "", [], {}):
                    return candidate
                candidate = details.get(name)
                if candidate not in (None, "", [], {}):
                    return candidate
                candidate = raw.get(name)
                if candidate not in (None, "", [], {}):
                    return candidate
            return default

        def inline(value_to_render: Any) -> str:
            return self._text(value_to_render)

        def suffix(*pairs: tuple[str, Any]) -> str:
            return " ".join(f"{name}={inline(item)}" for name, item in pairs if item not in (None, "", [], {}))

        def fact(tag: str, key: str, value_to_render: Any, *extra: tuple[str, Any]) -> str:
            line = f"{key}: {inline(value_to_render)}"
            tail = suffix(*extra)
            if tail:
                line += f" {tail}"
            return f"{known['time']} [{tag}] {line}\n"

        def judgement(tag: str, name: str, status: Any, *extra: tuple[str, Any]) -> str:
            line = f"判定: {name}={inline(status)}"
            tail = suffix(*extra)
            if tail:
                line += f" {tail}"
            return f"{known['time']} [{tag}] {line}\n"

        def raw_value(*names: str, default: Any = "") -> Any:
            for name in names:
                candidate = raw.get(name)
                if candidate not in (None, "", [], {}):
                    return candidate
                candidate = value(name)
                if candidate not in (None, "", [], {}):
                    return candidate
            return default

        def judgement_status(default: Any = "") -> Any:
            return value("tool_status", "wakeup_status", "command_status", "online_status", "player_status", "status", default=default)

        if event_name == "FIXED_FACT":
            key = str(value("fact_key", default="DEVICE")).upper()
            if key not in LOG_FACT_KEYS:
                key = "DEVICE_" + key
            return fact(str(value("tag", default="DEVICE")).upper(), key, value("fact_value"), ("证据", value("evidence")))
        if event_name == "FIXED_JUDGEMENT":
            return judgement(str(value("tag", default="RESULT")).upper(), value("judgement_name", default="结果"), value("judgement_status", "status", default=""), ("原因", value("reason")), ("证据", value("evidence")))

        tag = "EVENT"
        line = ""
        if event_name in {"CASE_WINDOW_OPENED", "CASE_STARTED"}:
            tag = "CASE"
            line = "START "
            line += suffix(
                ("场景", value("scenario", default=metadata.get("scenario", ""))),
                ("文本", value("input_text", "text", default=metadata.get("input_text", ""))),
                ("case_id", case_id),
                ("epoch", known.get("epoch", "")),
            )
            return f"{known['time']} [{tag} {case_prefix}] {line}\n"
        if event_name in {"CASE_WINDOW_CLOSED", "CASE_CLOSED"}:
            tag = "CASE"
            line = suffix(("END", "END"), ("case_id", case_id), ("原因", known.get("reason", "")), ("epoch", known.get("epoch", "")))
            return f"{known['time']} [{tag} {case_prefix}] {line}\n"
        if event_name == "BROADCAST_STARTED":
            tag = "ACTION"
            audio = value("audio_file", "audio", default=metadata.get("audio_path", ""))
            stem = Path(str(audio)).stem if audio else ""
            label = value("playback_name", "action", default="default_wake" if any(token in stem.lower() for token in ("wake", "wakeup", "唤醒")) else "command")
            text = value("spoken_text", "input_text", "text", default=metadata.get("input_text", ""))
            lines = [f"{known['time']} [{tag}] 播放={inline(label)} 文本={inline(text)} 文件={inline(audio)}"]
            if audio:
                audio_text = str(audio)
                if audio_text.lower().startswith(("http://", "https://")):
                    key = "PLAY_URL"
                elif audio_text.lower().endswith(".tone"):
                    key = "OFFLINE_TONE"
                else:
                    key = "AUDIO_FILE"
                if key != "AUDIO_FILE":
                    lines.append(f"{known['time']} [{tag}] {key}: {inline(audio)}")
            if value("broadcast_id"):
                lines.append(f"{known['time']} [{tag}] BROADCAST_ID: {inline(value('broadcast_id'))}")
            return "\n".join(lines) + "\n"
        if event_name in {"WAKE_WORD_VERIFIED", "WAKEUP", "RAW_WAKEUP"}:
            tag = "DEVICE"
            raw_values = raw.get("raw_values") if isinstance(raw.get("raw_values"), Mapping) else raw
            keyword = raw_values.get("keyword", value("keyword", "wake_keyword"))
            line = fact(tag, "WAKE", keyword, ("播报ID", value("broadcast_id")), ("证据", value("evidence")))
            return line + judgement("RESULT", "唤醒", judgement_status(known.get("status", "")), ("播报ID", value("broadcast_id")))
        if event_name in {"RAW_RECOGNITION", "RECOGNITION_RAW_RECORDED"} and str(value("recognition_source", "source")).lower() == "offline":
            tag = "DEVICE"
            keyword = raw.get("keyword", "")
            intent = raw.get("intent", "")
            asr = raw.get("text", raw.get("asr_text", ""))
            lines = []
            if keyword:
                lines.append(fact(tag, "OFFLINE_ASR", keyword, ("播报ID", value("broadcast_id"))))
            if intent:
                lines.append(fact(tag, "OFFLINE_INTENT", intent, ("播报ID", value("broadcast_id"))))
            if asr:
                lines.append(fact(tag, "OFFLINE_TEXT", asr, ("播报ID", value("broadcast_id"))))
            if normalized:
                normalized_text = normalized.get("text", normalized.get("normalized", normalized.get("command", "")))
                if normalized_text:
                    lines.append(fact(tag, "OFFLINE_NORMALIZED", normalized_text, ("播报ID", value("broadcast_id"))))
            lines.append(judgement("RESULT", "离线识别", judgement_status(known.get("status", "")), ("播报ID", value("broadcast_id")), ("配对", value("association_status", "association"))))
            return "".join(lines)
        if event_name == "ONLINE_REQUEST_RECORDED":
            tag = "ONLINE"
            request_id = value("request_id", "requestId", "correlation_id") or raw.get("request_id", raw.get("requestId", ""))
            return fact(tag, "REQUEST_ID", request_id, ("播报ID", value("broadcast_id")))
        if event_name in {"ONLINE_RESPONSE", "ONLINE_RECOGNITION", "RAW_RECOGNITION", "RECOGNITION_RAW_RECORDED"} and str(value("recognition_source", "source")).lower() == "online":
            tag = "ONLINE"
            request_id = value("request_id", "requestId", "correlation_id") or raw.get("request_id", raw.get("requestId", ""))
            response_id = value("response_id", "responseId") or raw.get("response_id", raw.get("responseId", ""))
            asr = raw.get("asr_text", raw.get("text", raw.get("asr", "")))
            correlation = value("correlation_valid", "valid", default="")
            latency = value("recognition_latency_ms", "elapsed_ms", "duration_ms")
            lines = []
            if request_id:
                lines.append(fact(tag, "REQUEST_ID", request_id, ("播报ID", value("broadcast_id"))))
            if response_id:
                lines.append(fact(tag, "RESPONSE_ID", response_id, ("播报ID", value("broadcast_id"))))
            if asr:
                lines.append(fact(tag, "ONLINE_ASR", asr, ("播报ID", value("broadcast_id"))))
            if latency not in (None, "", "-"):
                lines.append(fact(tag, "ASR_LATENCY_MS", latency, ("播报ID", value("broadcast_id"))))
            pair_status = "PASS" if correlation is True or str(correlation).upper() == "PASS" else ("FAIL" if correlation is False else correlation)
            lines.append(judgement("RESULT", "在线识别", judgement_status(pair_status), ("配对", pair_status), ("播报ID", value("broadcast_id"))))
            return "".join(lines)
        if event_name.startswith("PLAYER_") or event_name.startswith("HOST_AUDIO_") or event_name in {"PLAYER_LIFECYCLE", "BROADCAST_FAILED", "BROADCAST_ENDED"}:
            tag = "PLAYER"
            marker = value("marker", "raw_marker", "player_marker", default=event_name)
            state = value("lifecycle_status", "player_state", "device_playback_status", "status", default=known.get("status", ""))
            state_name = str(state).upper()
            if state_name.startswith("DEVICE_"):
                state_name = state_name.removeprefix("DEVICE_")
            if state_name in {"PROCESS_STARTED", "START", "RUNNING"}:
                state = "playing"
            elif state_name in {"COMPLETED", "PROBE_COMPLETED", "END", "STOP", "STOPPED"}:
                state = "stop"
            elif state_name in {"REQUESTED", "PROBE_REQUESTED"}:
                state = "request"
            else:
                state = state_name.lower()
            status = "PASS" if state in {"playing", "stop"} else ("FAIL" if state in {"error", "timeout", "blocked", "failed"} else "OBSERVED")
            return fact(tag, "PLAYER", state, ("播报ID", value("broadcast_id")), ("证据", value("evidence"))) + judgement("RESULT", "播放器", status, ("播报ID", value("broadcast_id")))
        if event_name == "CASE_RESULT":
            tag = "RESULT"
            case = raw.get("case", {}) if isinstance(raw.get("case", {}), Mapping) else {}
            facts = case.get("facts", {}) if isinstance(case, Mapping) and isinstance(case.get("facts", {}), Mapping) else {}
            wake = facts.get("wake", {}) if isinstance(facts.get("wake", {}), Mapping) else {}
            asr = facts.get("asr", {}) if isinstance(facts.get("asr", {}), Mapping) else {}
            online = facts.get("online", {}) if isinstance(facts.get("online", {}), Mapping) else {}
            player = facts.get("player", {}) if isinstance(facts.get("player", {}), Mapping) else {}
            player_status = str(player.get("status", player.get("device_playback_status", ""))).upper()
            if player_status in {"COMPLETED", "END", "OBSERVED"}:
                player_status = "PASS"
            elif player_status in {"REQUESTED", "RUNNING", "UNVERIFIED", ""}:
                player_status = "OBSERVED"
            return judgement("RESULT", "本轮", known.get("status", case.get("reviewed_status", case.get("raw_status", ""))), ("唤醒", wake.get("status", "")), ("离线识别", asr.get("status", facts.get("command_status", ""))), ("在线识别", online.get("status", facts.get("online_status", ""))), ("播放器", player_status), ("异常", known.get("reason", "")), ("case_id", case_id))
        if event_name == "OBSERVED_TAGS":
            tag_items = raw_items or details.get("raw_tags", [])
            lines: list[str] = []
            channel = str(value("channel", default="DEVICE")).upper()
            for item in tag_items if isinstance(tag_items, list) else []:
                if not isinstance(item, Mapping):
                    continue
                key = str(item.get("tag_name") or "DEVICE").upper()
                if key == "KEYWORD" and channel in {"COMMAND", "OFFLINE_RECOGNITION"}:
                    key = "OFFLINE_ASR"
                elif key == "INTENT" and channel in {"COMMAND", "OFFLINE_RECOGNITION"}:
                    key = "OFFLINE_INTENT"
                if key not in LOG_FACT_KEYS:
                    key = "DEVICE_" + key
                lines.append(fact("DEVICE", key, item.get("raw_value"), ("证据", item.get("evidence", ""))))
            for name, item in normalized.items():
                key = str(name).upper()
                if key in LOG_FACT_KEYS:
                    lines.append(fact("DEVICE", key, item))
            tool_status = value("tool_status", "status", default="")
            if tool_status:
                lines.append(judgement("RESULT", channel, tool_status, ("原因", value("tool_reason", "reason"))))
            return "".join(lines) or fact("SYSTEM", "OBSERVATION", message)
        if event_name == "ROUND_EXCEPTION_SUMMARY":
            snapshot = raw if isinstance(raw, Mapping) else {}
            counts = snapshot.get("exception_counts", {}) if isinstance(snapshot, Mapping) else {}
            total = snapshot.get("exception_total", 0) if isinstance(snapshot, Mapping) else 0
            line = suffix(("轮次", snapshot.get("completed_cases", known.get("round", ""))), ("当前", f"{snapshot.get('current_case_id', case_id)}:{snapshot.get('current_status', known.get('status', ''))}"), ("累计异常", counts), ("异常总数", total))
            return f"{known['time']} [SUMMARY] {line}\n\n"
        if event_name.startswith("SERIAL_COMMAND") or event_name.startswith("PROFILE_RECOVERY"):
            tag = "COMMAND"
        elif event_name in {"TASK_ANOMALY", "STICKY_FATAL", "TOOL_EXCEPTION"}:
            tag = "ERROR"
        if tag not in LOG_NODE_LABELS:
            tag = "SYSTEM"
        raw_hint = ""
        if event_name == "OBSERVED_TAGS":
            raw_hint = json.dumps({"normalized": normalized, **details}, ensure_ascii=False, sort_keys=True, default=str)
        elif raw:
            if event_name in {"RAW_RECOGNITION", "RECOGNITION_RAW_RECORDED"}:
                raw_hint = raw
            elif event_name in {"OBSERVATION_EVIDENCE", "TOOL_RECORD", "EXTERNAL_TOOL_OUTPUT"}:
                raw_hint = raw.get("events", raw.get("output", raw)) if isinstance(raw, Mapping) else (raw_text or raw)
        error_code = value("code", "anomaly_code", default="")
        if event_name in {"TASK_STARTED", "TASK_CONFIG"}:
            return fact("SYSTEM", "TASK", message, ("设备", value("device")), ("端口", value("port_role")))
        if event_name == "DEVICE_RESTART_DETECTED":
            restart_value = value("restart_line", "raw_line", default="detected")
            return fact("DEVICE", "RESTART", restart_value, ("epoch", known.get("epoch", "")), ("证据", value("evidence"))) + judgement("RESULT", "重启恢复", "RETRY", ("epoch", known.get("epoch", "")))
        if event_name == "PROFILE_RECOVERY_WAIT_INIT":
            return fact("DEVICE", "INIT_WAIT", "waiting", ("超时", value("timeout_s", default="")))
        if event_name == "PROFILE_RECOVERY_USE_OBSERVED_INIT":
            return fact("SYSTEM", "初始化证据", "已观察到", ("证据", value("evidence")))
        if event_name == "PROFILE_RECOVERY_STABILIZING":
            return fact("DEVICE", "INIT_STABLE", "waiting", ("耗时", value("elapsed_ms", default="")))
        if event_name.startswith("SERIAL_COMMAND") or event_name.startswith("PROFILE_RECOVERY"):
            if event_name == "PROFILE_RECOVERY_CANCELLED":
                return judgement("RESULT", "重启恢复", "CANCELLED", ("原因", known.get("reason", "")))
            if event_name == "PROFILE_RECOVERY_RESULT":
                return judgement("RESULT", "初始化", known.get("status", ""), ("原因", known.get("reason", "")))
            command = value("command", default="initialization")
            action_label = value("action_label", default="")
            reply = value("reply", "direct_reply", default="")
            attempt = f"{value('attempt')}/{value('max_attempts')}" if value("attempt") else ""
            command_text = str(command)
            if "log" in command_text.lower() and any(char.isdigit() for char in command_text):
                key = "LOG_LEVEL"
                command_value = command_text.rsplit(None, 1)[-1]
            elif action_label:
                key = str(action_label)
                command_value = command_text
            else:
                key = "COMMAND"
                command_value = command_text
            lines = [fact("COMMAND", key, command_value, ("尝试", attempt), ("回执", reply), ("证据", value("evidence")))]
            status = judgement_status(known.get("status", ""))
            if status or error_code:
                name = "日志等级" if key == "LOG_LEVEL" else (str(action_label) or "初始化")
                lines.append(judgement("RESULT", name, status or ("FAIL" if error_code else "-"), ("异常", error_code), ("原因", known.get("reason", ""))))
            return "".join(lines)
        if event_name in {"TASK_FINISHED"}:
            summary = raw if isinstance(raw, Mapping) else {}
            return judgement("RESULT", "任务", known.get("status", ""), ("完成", summary.get("completed", "")), ("通过", summary.get("counts", {}).get("PASS", "") if isinstance(summary.get("counts"), Mapping) else ""), ("异常", summary.get("exception_total", "")), ("原因", known.get("reason", "")))
        line = suffix(("状态", known.get("status", "")), ("异常", error_code), ("原因", known.get("reason", "")), ("重试", f"{value('attempt')}/{value('max_attempts')}" if value("attempt") else ""), ("证据", known.get("evidence", "")), ("说明", message))
        if raw_text and event_name in {"EXTERNAL_TOOL_OUTPUT", "TOOL_RECORD"} and raw_text not in line:
            line += f" 原始输出={raw_text}"
        return f"{known['time']} [{tag}] {line}\n"

    def configure(self, payload: Mapping[str, Any]) -> None:
        """Record a non-sensitive resolved configuration in the sole tool log."""
        self.emit("TASK_CONFIG", message="已记录任务解析配置。", phase="preflight", raw=dict(payload))

    def emit_fact(
        self,
        key: str,
        value: Any,
        *,
        tag: str = "DEVICE",
        evidence: Any = "",
        **fields: Any,
    ) -> None:
        """Emit one fixed raw fact; regex text never belongs in tool.log."""
        normalized_key = str(key or "").strip().upper()
        if normalized_key not in LOG_FACT_KEYS:
            raise ValueError(f"unsupported tool.log fact key: {key}")
        tag_name = str(tag or "DEVICE").upper()
        if tag_name not in {"ACTION", "DEVICE", "ONLINE", "PLAYER", "COMMAND", "SYSTEM"}:
            raise ValueError(f"unsupported tool.log fact tag: {tag}")
        self.timeline_fact(
            str(fields.get("case_id") or ""), normalized_key, value,
            tag=tag_name, evidence=(evidence if isinstance(evidence, (list, tuple, set)) else [evidence]),
            port=str(fields.get("port") or ""), role=str(fields.get("role") or ""),
            phase=str(fields.get("phase") or ""), identity=str(fields.get("identity") or ""),
        )

    def emit_judgement(self, name: str, status: str, *, tag: str = "RESULT", **fields: Any) -> None:
        """Emit a separate tool-derived judgement line after a raw fact."""
        if str(tag or "RESULT").upper() not in {"RESULT", "ERROR", "SYSTEM"}:
            raise ValueError(f"unsupported tool.log judgement tag: {tag}")
        if not str(name or "").strip():
            raise ValueError("tool.log judgement name cannot be empty")
        # Historical adapters may still call this method.  A verdict is now
        # rendered only once by ``record_case`` after the observation window
        # closes, so an intermediate judgement must not leak to tool.log.
        return None

    def emit(self, event: str, *, message: str = "", level: str = "INFO", task_log: bool = True, **fields: Any) -> None:
        """Append one fixed-field execution block to ``tool.log``.

        ``task_log`` remains a compatibility flag for existing adapters.  Raw
        serial line mirroring is intentionally suppressed because continuous
        device output belongs only in ``serial_logs/``.
        """
        if self.closed:
            return
        if event == "SERIAL_LINE" and not task_log:
            return
        block = self._tool_block(event, level, message or event, fields)
        if block:
            self._append_timeline_line(block)
        # When a formal runtime has enabled the timeline mirror, the exact
        # rendered line has already reached stdout.  Printing this legacy
        # compatibility summary as well would make terminal output diverge
        # from tool.log.
        if task_log and self._terminal_stream is None and not self._legacy_stdout_disabled:
            try:
                print(f"{now_human()} [{level.upper()}] {message or event}", flush=True)
            except (OSError, ValueError):
                # A parent/CI pipe may close while the durable tool.log is
                # still writable.  Do not turn that transport loss into a
                # test or device failure during finalization.
                self._legacy_stdout_disabled = True

    def write_tool_log(self, name: str, content: str, *, append: bool = True) -> Path:
        raise RuntimeError("项目适配器不得直接写 tool.log；请提交 RawLogRecord 或调用公开动作 API")

    def append_tool_jsonl(self, name: str, payload: Mapping[str, Any]) -> Path:
        raise RuntimeError("项目适配器不得写独立 JSON 工具日志；请使用 results.csv 的结构化事实列")

    def emit_observation(
        self,
        channel: str,
        tags: Sequence[RawTag | Mapping[str, Any]],
        *,
        event: str = "OBSERVED_TAGS",
        normalized: Mapping[str, Any] | None = None,
        judgement: ToolJudgement | None = None,
        level: str = "INFO",
        task_log: bool = True,
        human_log: bool = True,
        **fields: Any,
    ) -> dict[str, Any]:
        """同时保存设备原始标签和工具侧判断，并镜像关键行。"""
        raw_tags = raw_tags_from_mappings(tags)
        normalized_payload = dict(normalized or {})
        judgement_payload = judgement.to_dict() if judgement else {}
        message = render_observation(channel, raw_tags, normalized=normalized_payload, judgement=judgement)
        event_fields = {
            "channel": channel,
            "raw_tags": [item.to_dict() for item in raw_tags],
            "normalized": normalized_payload,
            "tool_judgement": judgement_payload,
            **fields,
        }
        if judgement:
            event_fields.update({
                "tool_status": judgement.tool_status,
                "tool_reason": judgement.tool_reason,
                "expected": dict(judgement.expected),
                "actual": dict(judgement.actual),
                "duration_ms": judgement.duration_ms,
                "evidence_refs": list(judgement.evidence_refs),
            })
        if human_log:
            self.emit(event, message=message, level=level, task_log=task_log, **event_fields)
        return event_fields

    @staticmethod
    def _flatten_mapping(value: Any) -> dict[str, Any]:
        return dict(value) if isinstance(value, Mapping) else {}

    @staticmethod
    def _join_codes(values: Iterable[Any]) -> str:
        flattened: list[str] = []
        for value in values:
            if isinstance(value, str):
                flattened.append(value)
            elif isinstance(value, Iterable) and not isinstance(value, (bytes, bytearray, Mapping)):
                flattened.extend(str(item) for item in value)
            elif value is not None:
                flattened.append(str(value))
        return ";".join(sorted({item for item in flattened if item.strip()}))

    @staticmethod
    def _csv_value(value: Any) -> Any:
        if isinstance(value, (Mapping, list, tuple, set)):
            return json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)
        return value

    @property
    def cases_frozen(self) -> bool:
        return self._cases_frozen

    def case_metadata(self, case_id: str) -> dict[str, Any]:
        """Return the frozen human-facing metadata for one case."""
        return dict(self._case_metadata.get(str(case_id), {}))

    def require_cases_frozen(self, action: str) -> None:
        """Prevent a project adapter from changing its corpus after device I/O."""
        if not self._cases_frozen:
            message = f"执行 {action} 前必须先冻结 cases.csv。"
            self.emit("CASES_NOT_FROZEN", level="ERROR", message=message, phase="preflight", action_id=action)
            raise RuntimeError(message)

    def require_case_declared(self, case_id: str, action: str) -> None:
        """Ensure a lazy case is durable before its first device action."""
        if str(case_id) in self._case_positions:
            return
        message = f"执行 {action} 前必须先声明当前用例并写入 cases.csv。"
        self.emit("CASE_NOT_DECLARED", level="ERROR", message=message, phase="preflight", action_id=action, case_id=case_id)
        raise RuntimeError(message)

    def begin_lazy_cases(
        self,
        *,
        scenario: str,
        planned_total: int | None = None,
        random_seed: Any = "",
        profile_version: Any = "",
        profile_sha256: Any = "",
    ) -> None:
        """Freeze task identity without materialising a random pressure corpus."""
        if self._cases_frozen or self._lazy_case_mode:
            raise RuntimeError("cases.csv is already initialized for this task")
        self._lazy_case_mode = True
        self._cases_frozen = True
        self._planned_case_count = max(0, int(planned_total or 0))
        self._lazy_case_identity = {
            "scenario": str(scenario),
            "random_seed": random_seed,
            "profile_version": profile_version,
            "profile_sha256": profile_sha256,
        }
        self.emit(
            "LAZY_CASE_LEDGER_READY",
            message="已冻结惰性用例任务身份，后续用例将在动作前逐条写入 cases.csv。",
            phase="preflight",
            status="PASS",
            raw={**self._lazy_case_identity, "planned_total": self._planned_case_count},
        )

    def declare_case(self, case: CaseSpec | Mapping[str, Any]) -> int:
        """Persist one immutable lazy case before any playback or serial write."""
        if not self._lazy_case_mode:
            raise RuntimeError("declare_case is only available after begin_lazy_cases")
        if isinstance(case, CaseSpec):
            metadata = dict(case.metadata)
            row = {
                "case_id": case.case_id,
                "scenario": metadata.get("scenario") or case.domain or self._lazy_case_identity["scenario"],
                "input_text": case.text,
                "audio_file": case.audio_path or "",
                "case_contract": metadata.get("timeline", {}),
                "timeline": metadata.get("timeline", {}),
                "source_file": metadata.get("source_file", ""),
                "source_sha256": metadata.get("source_sha256", ""),
            }
        else:
            raw = dict(case)
            row = {
                "case_id": raw.get("case_id", ""),
                "scenario": raw.get("scenario", raw.get("domain", self._lazy_case_identity["scenario"])),
                "input_text": raw.get("input_text", raw.get("text", "")),
                "audio_file": raw.get("audio_file", raw.get("audio_path", "")),
                "case_contract": raw.get("timeline", raw.get("case_contract", {})),
                "timeline": raw.get("timeline", {}),
                "source_file": raw.get("source_file", ""),
                "source_sha256": raw.get("source_sha256", ""),
            }
        case_id = str(row["case_id"] or "").strip()
        if not case_id:
            raise ValueError("lazy case requires case_id")
        with self._lock:
            if case_id in self._case_positions:
                raise RuntimeError(f"lazy case is immutable and already declared: {case_id}")
            order = self._declared_case_count + 1
            audio_path = Path(str(row["audio_file"])) if row["audio_file"] else None
            self._cases_writer.writerow({
                "case_order": order,
                **row,
                "audio_sha256": sha256_file(audio_path) if audio_path and audio_path.is_file() else "",
                "random_seed": self._lazy_case_identity["random_seed"],
                "profile_version": self._lazy_case_identity["profile_version"],
                "profile_sha256": self._lazy_case_identity["profile_sha256"],
            } | {name: self._csv_value(value) for name, value in row.items()})
            self._cases.flush()
            self._case_positions[case_id] = order
            self._case_metadata[case_id] = {
                "scenario": row.get("scenario", ""),
                "input_text": row.get("input_text", ""),
                "audio_path": row.get("audio_file", ""),
                "timeline": row.get("timeline", {}),
                "profile_version": self._lazy_case_identity["profile_version"],
                "profile_sha256": self._lazy_case_identity["profile_sha256"],
            }
            self._declared_case_count = order
        self.emit(
            "LAZY_CASE_DECLARED",
            message=f"已声明第 {order} 条惰性用例。",
            phase="case_declaration",
            case_id=case_id,
            round=order,
            status="PASS",
            raw={"case_order": order, **row},
        )
        return order

    def freeze_cases(
        self,
        cases: Iterable[CaseSpec | Mapping[str, Any]],
        *,
        random_seed: Any = "",
        profile_version: Any = "",
        profile_sha256: Any = "",
    ) -> int:
        """Freeze the final case order before the first device action."""
        if self._cases_frozen:
            raise RuntimeError("cases.csv is already frozen for this task")
        rows = list(cases)
        with self._lock:
            for order, value in enumerate(rows, start=1):
                if isinstance(value, CaseSpec):
                    metadata = dict(value.metadata)
                    row = {
                        "case_id": value.case_id,
                        "scenario": metadata.get("scenario") or value.domain or "",
                        "input_text": value.text,
                        "audio_file": value.audio_path or "",
                        "case_contract": metadata.get("timeline", {}),
                        "timeline": metadata.get("timeline", {}),
                        "source_file": metadata.get("source_file", ""),
                        "source_sha256": metadata.get("source_sha256", ""),
                    }
                else:
                    raw = dict(value)
                    row = {
                        "case_id": raw.get("case_id", ""),
                        "scenario": raw.get("scenario", raw.get("domain", "")),
                        "input_text": raw.get("input_text", raw.get("text", "")),
                        "audio_file": raw.get("audio_file", raw.get("audio_path", "")),
                        "case_contract": raw.get("timeline", raw.get("case_contract", {})),
                        "timeline": raw.get("timeline", {}),
                        "source_file": raw.get("source_file", ""),
                        "source_sha256": raw.get("source_sha256", ""),
                    }
                audio_path = Path(str(row["audio_file"])) if row["audio_file"] else None
                self._cases_writer.writerow({
                    "case_order": order,
                    **row,
                    "audio_sha256": sha256_file(audio_path) if audio_path and audio_path.is_file() else "",
                    "random_seed": random_seed,
                    "profile_version": profile_version,
                    "profile_sha256": profile_sha256,
                } | {name: self._csv_value(value) for name, value in row.items()})
                case_id = str(row.get("case_id") or "").strip()
                if case_id and case_id not in self._case_positions:
                    self._case_positions[case_id] = order
                    self._case_metadata[case_id] = {
                        "scenario": row.get("scenario", ""),
                        "input_text": row.get("input_text", ""),
                        "audio_path": row.get("audio_file", ""),
                        "timeline": row.get("timeline", {}),
                        "profile_version": profile_version,
                        "profile_sha256": profile_sha256,
                    }
            self._cases.flush()
        self._cases_frozen = True
        self._frozen_case_count = len(rows)
        self._planned_case_count = len(rows)
        self.emit(
            "CASES_FROZEN",
            message=f"已冻结本次压测用例，共 {len(rows)} 条。",
            phase="preflight",
            status="PASS",
            raw={"case_count": len(rows), "random_seed": random_seed, "profile_version": profile_version},
        )
        return len(rows)

    def set_epoch(self, epoch: int, *, reason: str = "") -> None:
        next_epoch = max(0, int(epoch))
        if next_epoch == self.current_epoch:
            return
        previous = self.current_epoch
        self.current_epoch = next_epoch
        self.emit(
            "SESSION_EPOCH_CHANGED",
            level="WARN" if previous else "INFO",
            message=f"设备会话 epoch 已切换为 {next_epoch}。",
            epoch=next_epoch,
            reason=reason,
            raw={"previous_epoch": previous, "current_epoch": next_epoch},
        )
        for listener in tuple(self._epoch_listeners):
            try:
                listener(next_epoch, reason=reason)
            except Exception as error:
                self.record_anomaly(
                    "EPOCH_LISTENER_EXCEPTION",
                    "设备会话切换通知失败。",
                    error=f"{type(error).__name__}: {error}",
                )

    def register_epoch_listener(self, listener: Any) -> None:
        if callable(listener):
            self._epoch_listeners.append(listener)

    def add_check(
        self,
        case_id: str,
        name: str,
        status: str,
        *,
        required: bool = True,
        reason: str = "",
        evidence: Iterable[str] = (),
        **fields: Any,
    ) -> dict[str, Any]:
        """Register a required/optional check used to derive a case status."""
        record = {
            "name": str(name),
            "status": str(status).upper(),
            "required": bool(required),
            "reason": reason,
            "evidence": [str(item) for item in evidence],
            **fields,
        }
        self.checks.setdefault(case_id, []).append(record)
        self.emit(
            "CASE_CHECK",
            level="ERROR" if record["status"] == "FAIL" else "INFO",
            message=f"用例检查 {name}: {record['status']}。",
            case_id=case_id,
            status=record["status"],
            reason=reason,
            evidence=record["evidence"],
            raw={"required": required, **fields},
        )
        return record

    def derive_case_status(self, case_id: str, fallback: str) -> tuple[str, list[dict[str, Any]]]:
        checks = list(self.checks.pop(case_id, ()))
        required = [item for item in checks if item["required"]]
        states = {item["status"] for item in required}
        if "FAIL" in states:
            return "FAIL", checks
        if "BLOCKED" in states:
            return "BLOCKED", checks
        if required and states <= {"PASS"}:
            return "PASS", checks
        return fallback, checks

    def configure_health_policy(self, policy: Mapping[str, Any] | None) -> None:
        self.health_policy = dict(policy or {})
        self.emit("HEALTH_POLICY", message="已加载连续异常健康策略。", raw=self.health_policy)

    def record_health(self, category: str, *, failed: bool, case_id: str = "", **fields: Any) -> dict[str, Any]:
        """Track continuous failures without stopping a runnable pressure task."""
        key = str(category).upper()
        count = self.health_streaks.get(key, 0) + 1 if failed else 0
        self.health_streaks[key] = count
        rule = self._flatten_mapping(self.health_policy.get(key) or self.health_policy.get(key.lower()))
        threshold = int(rule.get("threshold", 0) or 0)
        crossed = bool(failed and threshold > 0 and count >= threshold)
        record = {"category": key, "failed": failed, "consecutive_count": count, "threshold": threshold, "crossed": crossed}
        if crossed:
            handling = str(rule.get("handling") or "snapshot_and_continue")
            snapshot = {
                "case_id": case_id,
                "epoch": self.current_epoch,
                "category": key,
                "consecutive_count": count,
                "evidence": fields.get("evidence") or fields.get("evidence_refs") or [],
            }
            self.record_anomaly(
                f"HEALTH_{key}_THRESHOLD",
                f"连续 {count} 次 {key} 达到 profile 阈值。",
                case_id=case_id,
                handling=handling,
                **fields,
            )
            self.emit(
                "HEALTH_POLICY_TRIGGERED",
                level="WARN",
                message=f"连续异常达到阈值，执行策略：{handling}。",
                case_id=case_id,
                handling=handling,
                raw=record,
            )
            self.emit(
                "HEALTH_POLICY_SNAPSHOT",
                level="WARN",
                message="连续异常已记录当前证据快照。",
                case_id=case_id,
                phase="health_policy",
                handling=handling,
                raw=snapshot,
            )
            if "session" in handling or "recover" in handling:
                self.emit(
                    "HEALTH_SESSION_RECOVERY_REQUESTED",
                    level="WARN",
                    message="健康策略请求项目适配器恢复当前会话后继续执行。",
                    case_id=case_id,
                    phase="health_policy",
                    handling=handling,
                    raw=snapshot,
                )
            # Health thresholds request a project recovery callback but are not
            # task-stop conditions.  Only StopPolicy may request a task stop.
        return record

    def record_case(self, result: CaseResult) -> None:
        initial_status = result.reviewed_status or result.raw_status
        status, checks = self.derive_case_status(result.case_id, initial_status)
        if status != initial_status:
            result.reviewed_status = status
            result.reason = "; ".join(filter(None, [result.reason, "required_check_matrix"]))
        result.facts = {**result.facts, "checks": checks, "epoch": self.current_epoch}
        facts = dict(result.facts)
        timeline_contract = self._timeline_contract(result.case_id)
        timeline_result = self.timeline.close_case(
            result.case_id,
            status=status,
            reason=result.reason,
            current_anomaly_counts=self.anomaly_counts,
            expected_keys=timeline_contract["expected_keys"],
        )
        timeline_status = str(timeline_result.get("status") or status).upper()
        if timeline_status != status:
            status = timeline_status
            result.reviewed_status = status
            result.reason = str(timeline_result.get("reason") or result.reason)
        facts["timeline"] = timeline_result
        self.counts[status] = self.counts.get(status, 0) + 1
        self.completed_cases += 1
        if status not in NORMAL_CASE_STATUSES:
            self.exception_counts[status] = self.exception_counts.get(status, 0) + 1
        associations = list(facts.get("broadcast_recognition_associations", ()))
        raw_codes = facts.get("anomaly_codes", ())
        if isinstance(raw_codes, str):
            raw_codes = [raw_codes]
        anomaly_codes = [*raw_codes, *[item.get("reason", "") for item in associations if isinstance(item, Mapping) and item.get("status") != "PASS"]]
        profile_version = self._case_metadata.get(result.case_id, {}).get("profile_version", "")
        profile_sha256 = self._case_metadata.get(result.case_id, {}).get("profile_sha256", "")
        with self._lock:
            row = {
                "round": self.completed_cases,
                "case_id": result.case_id,
                "started_at": facts.get("started_at", ""),
                "ended_at": now_iso(),
                "epoch": self.current_epoch,
                "scenario": facts.get("scenario", ""),
                "input_text": facts.get("input_text", ""),
                "audio_file": safe_basename(facts.get("audio_path", self._case_metadata.get(result.case_id, {}).get("audio_path", ""))),
                "audio_sha256": facts.get("audio_sha256", ""),
                "profile_version": profile_version,
                "profile_sha256": profile_sha256,
                "raw_fact_counts": json.dumps(timeline_result.get("raw_counts", {}), ensure_ascii=False, sort_keys=True),
                "logical_fact_counts": json.dumps(timeline_result.get("logical_counts", {}), ensure_ascii=False, sort_keys=True),
                "association": json.dumps(facts.get("association", {}), ensure_ascii=False, sort_keys=True, default=str),
                "primary_reason": timeline_result.get("reason", result.reason),
                "raw_status": result.raw_status,
                "reviewed_status": result.reviewed_status or "",
                "final_status": status,
                "anomaly_codes": self._join_codes(anomaly_codes),
                "reason": result.reason,
                "evidence": self._join_codes(result.evidence),
                "facts_json": json.dumps(facts, ensure_ascii=False, sort_keys=True, default=str),
            }
            self._writer.writerow({name: self._csv_value(value) for name, value in row.items()})
            self._csv.flush()
        self._record_round_exception_summary(result.case_id, status)

    def _record_round_exception_summary(self, case_id: str, status: str) -> None:
        """Print and persist the cumulative, task-level exception snapshot."""
        snapshot = {
            "completed_cases": self.completed_cases,
            "current_case_id": case_id,
            "current_status": status,
            "exception_counts": dict(sorted(self.exception_counts.items())),
            "exception_total": sum(self.exception_counts.values()),
            "anomaly_counts": dict(sorted(self.anomaly_counts.items())),
            "anomaly_total": sum(self.anomaly_counts.values()),
            "sticky_counts": self._sticky_counts(),
        }
        # ``TimelineLedger.close_case`` has already emitted the only human
        # round summary.  Keep this helper as the programmatic snapshot API.
        return None

    def _sticky_counts(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for item in self.sticky:
            code = str(item.get("code") or "UNKNOWN")
            counts[code] = counts.get(code, 0) + 1
        return dict(sorted(counts.items()))

    def update_progress(self, *, completed: int, target: int | None = None, **fields: Any) -> None:
        self.emit(
            "TASK_PROGRESS",
            message=f"当前进度：{completed}/{target if target is not None else '-'}。",
            round=completed,
            raw={
                "completed": completed,
                "target": target,
                "exception_counts": dict(sorted(self.exception_counts.items())),
                "anomaly_counts": dict(sorted(self.anomaly_counts.items())),
                **fields,
            },
        )

    def set_capability(self, name: str, status: str, reason: str = "", **fields: Any) -> None:
        self.capabilities[name] = {"status": status, "reason": reason, **fields}
        self.emit("CAPABILITY", message=f"能力 {name}: {status}；{reason}".rstrip("；"), task_log=True, capability=name, status=status, reason=reason, **fields)

    def add_sticky(self, code: str, message: str, **fields: Any) -> None:
        record = {"code": code, "message": message, "at": now_iso(), **fields}
        self.sticky.append(record)
        self.emit("STICKY_FATAL", level="ERROR", message=message, code=code, at=record["at"], **fields)

    def record_anomaly(self, code: str, message: str, **fields: Any) -> dict[str, Any]:
        """Record a recoverable task anomaly without hiding it behind a later pass."""
        normalized_code = str(code or "UNKNOWN_ANOMALY").strip().upper() or "UNKNOWN_ANOMALY"
        self.anomaly_counts[normalized_code] = self.anomaly_counts.get(normalized_code, 0) + 1
        record = {
            "code": normalized_code,
            "message": message,
            "at": now_iso(),
            "count": self.anomaly_counts[normalized_code],
            **fields,
        }
        evidence = fields.get("evidence_refs", fields.get("evidence", ()))
        if isinstance(evidence, (str, bytes)):
            evidence = [evidence]
        self.timeline.error(
            str(fields.get("case_id") or ""), normalized_code, message,
            evidence=evidence if isinstance(evidence, Iterable) else (),
            handling=str(fields.get("handling") or ""),
        )
        return record

    def register_closer(self, name: str, closer: Any) -> None:
        """登记可调用的资源关闭函数，按逆序执行且每项有界。"""
        if callable(closer):
            self._closers.append((name, closer))

    def request_stop(self, code: str, reason: str = "", **details: Any) -> bool:
        """Request a whitelist stop and leave an auditable timeline entry."""
        accepted = self.stop_policy.request(code, reason=reason, **details)
        if accepted:
            try:
                self.timeline.error(
                    str(details.get("case_id") or ""), code,
                    reason or code, evidence=details.get("evidence", ()), handling="任务受控收尾",
                )
            except OSError:
                pass
        else:
            self.record_anomaly(
                "REJECTED_STOP_REQUEST",
                "普通异常不得请求停止任务，已按当前轮异常处理。",
                requested_code=code,
                reason=reason,
                **details,
            )
        return accepted

    def check_runtime(self) -> str | None:
        return self.stop_policy.check(self.run_dir)

    def _reconcile_results(self) -> dict[str, Any]:
        """Recalculate final counts from the durable one-row-per-case ledger."""
        with self._lock:
            self._csv.flush()
        counts: dict[str, int] = {}
        rows: list[dict[str, str]] = []
        previous_field_limit = csv.field_size_limit()
        if previous_field_limit < RESULT_CSV_FIELD_LIMIT:
            csv.field_size_limit(RESULT_CSV_FIELD_LIMIT)
        with self.results_path.open("r", encoding="utf-8-sig", newline="") as handle:
            try:
                for row in csv.DictReader(handle):
                    rows.append(row)
                    state = str(row.get("final_status") or "").upper()
                    if state:
                        counts[state] = counts.get(state, 0) + 1
            finally:
                if previous_field_limit < RESULT_CSV_FIELD_LIMIT:
                    csv.field_size_limit(previous_field_limit)
        invalid = sum(counts.get(value, 0) for value in ("BLOCKED", "ABORTED", "SKIPPED"))
        valid = max(0, len(rows) - invalid)
        passed = counts.get("PASS", 0) + counts.get("EXPECTED", 0)
        first_failure = next((row for row in rows if row.get("final_status") not in NORMAL_CASE_STATUSES), None)
        return {
            "rows": len(rows),
            "counts": counts,
            "invalid": invalid,
            "valid": valid,
            "passed": passed,
            "first_failure": first_failure,
            "success_rate": round((passed / valid) * 100, 4) if valid else None,
        }

    def finalize(self, status: str, reason: str) -> dict[str, Any]:
        if self.closed:
            return dict(self._final_summary or {"status": status, "reason": reason})
        for name, closer in reversed(self._closers):
            try:
                closer()
            except Exception as error:  # cleanup must remain visible, never hide the result
                self.add_sticky("TOOL_EXCEPTION", f"资源收尾失败: {name}", resource=name, error=str(error))
        reconciliation = self._reconcile_results()
        self.counts = dict(reconciliation["counts"])
        final_status = status
        final_reason = reason
        if self.counts.get("FAIL", 0) and final_status in {"PASS", "WARN", "PASS_WITH_WARNINGS"}:
            final_status = "FAIL"
            final_reason = f"{reason}；results.csv 含 {self.counts['FAIL']} 个 FAIL 轮次"
        elif self.counts.get("BLOCKED", 0) and not self.counts.get("PASS", 0) and final_status in {"PASS", "WARN", "PASS_WITH_WARNINGS"}:
            final_status = "BLOCKED"
            final_reason = f"{reason}；results.csv 没有有效 PASS 轮次且含 BLOCKED"
        if self.sticky and final_status in {"PASS", "WARN"}:
            final_status = "FAIL"
            final_reason = f"{reason}；存在 sticky fatal: {self.sticky[-1].get('code', 'UNKNOWN')}"
        completed_rows = reconciliation["rows"]
        invalid = reconciliation["invalid"]
        valid = reconciliation["valid"]
        passed = reconciliation["passed"]
        summary = {
            "status": final_status,
            "reason": final_reason,
            "ended_at": now_iso(),
            "counts": self.counts,
            "exception_counts": dict(sorted(self.exception_counts.items())),
            "exception_total": sum(self.exception_counts.values()),
            "anomaly_counts": dict(sorted(self.anomaly_counts.items())),
            "anomaly_total": sum(self.anomaly_counts.values()),
            "sticky_counts": self._sticky_counts(),
            "capabilities": self.capabilities,
            "sticky_failures": self.sticky,
            "result_directory": str(self.run_dir),
            "completed": completed_rows,
            "planned": self._planned_case_count or self._frozen_case_count,
            "valid": valid,
            "success_rate": reconciliation["success_rate"],
            "first_failure": reconciliation["first_failure"],
        }
        self.emit(
            "TASK_FINISHED",
            message=f"任务结束: {final_status}；{final_reason}",
            status=final_status,
            reason=final_reason,
            raw=summary,
            handling="results.csv counts reconciled before final status",
        )
        for handle in (self._tool, self._csv, self._cases):
            if handle is not None:
                handle.close()
        self._final_summary = summary
        self.closed = True
        return summary

    def serial_log_path(self, port: str, role: str | None) -> Path:
        safe_port = str(port).replace("/", "_").replace("\\", "_")
        safe_role = str(role or "unknown").replace("/", "_").replace("\\", "_")
        return self.run_dir / "serial_logs" / f"serial_{safe_port}_{safe_role}.log"


class DeviceRuntime:
    """Small contract object; concrete serial/profile/playback adapters are injected."""

    def __init__(self, connection: ConnectionSpec, profile: Any, artifacts: TaskArtifacts):
        self.connection = connection
        self.profile = profile
        self.artifacts = artifacts
        self.started = False
        self.restart_recovery_monitor: Any | None = None

    def preflight(self) -> dict[str, Any]:
        self.artifacts.emit("PREFLIGHT", message="开始公共设备前置检查。", task_log=True, ports=self.connection.to_dict()["ports"])
        return {"ports": len(self.connection.ports), "profile": getattr(self.profile, "profile_id", None)}

    def start_restart_recovery(
        self,
        manager: Any,
        *,
        initialization_timeout_s: float = 10.0,
        poll_interval_s: float = 0.1,
        stable_for_s: float = 0.0,
    ) -> Any:
        """Continuously recover profile initialization after restart markers."""
        if self.restart_recovery_monitor is not None:
            return self.restart_recovery_monitor
        try:
            from .shell import ProfileRestartRecoveryMonitor
        except ImportError:  # direct execution fallback
            from shell import ProfileRestartRecoveryMonitor
        monitor = ProfileRestartRecoveryMonitor(
            self.profile,
            self.artifacts,
            manager,
            initialization_timeout_s=initialization_timeout_s,
            poll_interval_s=poll_interval_s,
            stable_for_s=stable_for_s,
        )
        monitor.start()
        self.restart_recovery_monitor = monitor
        self.started = True
        return monitor

    def recover_initialization(
        self,
        manager: Any,
        *,
        cursors: Mapping[str, int] | None = None,
        initialization_events: Iterable[Any] | None = None,
        recovery_reason: str = "startup",
    ) -> dict[str, Any]:
        """Verify all profile initialization commands after a completed boot.

        A successful first recovery also starts background restart monitoring.
        Commands and validation rules always come from the project profile.
        """
        try:
            from .shell import ProfileRecoveryStateMachine
        except ImportError:  # direct execution fallback
            from shell import ProfileRecoveryStateMachine
        recovery = self.profile.recovery if hasattr(self.profile, "recovery") else {}
        timeout_s = max(0.1, float(recovery.get("initialization_timeout_s", 10.0)))
        poll_interval_s = max(0.02, float(recovery.get("restart_poll_interval_s", 0.1)))
        stable_for_s = max(0.0, float(recovery.get("stable_for_s", 0.0) or 0.0))
        result = ProfileRecoveryStateMachine(self.profile, self.artifacts, manager).run(
            timeout_s,
            cursors=cursors,
            initialization_events=initialization_events,
            recovery_reason=recovery_reason,
            stable_for_s=stable_for_s,
        )
        if result.get("status") == "PASS":
            self.start_restart_recovery(
                manager,
                initialization_timeout_s=timeout_s,
                poll_interval_s=poll_interval_s,
                stable_for_s=stable_for_s,
            )
        return result

    def check_ready(self) -> str | None:
        """Return a restart/recovery stop reason before a project starts new work."""
        return self.artifacts.check_runtime()

    def close(self) -> None:
        if self.restart_recovery_monitor is not None:
            self.restart_recovery_monitor.stop()
            self.restart_recovery_monitor = None
        if self.started:
            self.artifacts.emit("RUNTIME_CLOSE", message="公共运行时已收尾。", task_log=True)
            self.started = False
